apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  ports:
    - port: 25565
  selector:
    app: minecraft
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - image: itzg/minecraft-server:latest
          name: minecraft
          env:
          ports:
            - containerPort: 25565
              name: minecraft
          volumeMounts:
            - name: minecraft-persistent-storage
              mountPath: /data
      volumes:
        - name: minecraft-persistent-storage
          persistentVolumeClaim:
            claimName: minecraft-pv-claim
